# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

platform :ios, '8.0'

target 'SalSideDemo' do

    pod 'AFNetworking', '~> 2.5'
    pod 'SDWebImage', '~>3.7'
    pod 'MBProgressHUD', '~> 0.9.2'
    
end

